Delivered-To: ted@hbgary.com
Received: by 10.223.109.204 with SMTP id k12cs258458fap;
        Thu, 28 Oct 2010 14:18:50 -0700 (PDT)
Received: by 10.224.186.10 with SMTP id cq10mr3997614qab.218.1288300730259;
        Thu, 28 Oct 2010 14:18:50 -0700 (PDT)
Return-Path: <nonreplyplease@mybizmail.org>
Received: from mybizmail.org ([69.10.53.14])
        by mx.google.com with SMTP id m23si3467908qck.134.2010.10.28.14.18.42;
        Thu, 28 Oct 2010 14:18:50 -0700 (PDT)
Received-SPF: neutral (google.com: 69.10.53.14 is neither permitted nor denied by best guess record for domain of nonreplyplease@mybizmail.org) client-ip=69.10.53.14;
Authentication-Results: mx.google.com; spf=neutral (google.com: 69.10.53.14 is neither permitted nor denied by best guess record for domain of nonreplyplease@mybizmail.org) smtp.mail=nonreplyplease@mybizmail.org
Message-ID: <44026586.5D5ED320@mybizmail.org>
Date: Thu, 28 Oct 2010 13:50:05 -0700
From: "NASBC - Small Business Contractors" <nonreplyplease@mybizmail.org>
MIME-Version: 1.0
To: <penny@hbgary.com>
Cc: <ted@hbgary.com>
Subject: California  Small Business Federal Contractors
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

+  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +
3rd Annual National Small Business Contracting Summit - West Coast 
(Nov 2-3, 2010 - San Diego, CA)

Presented by the National Association of Small Business Contractors
+  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +

Did you know how much these federal agencies spent with California firms
last year?

GSA - $1 Billion
Veterans Affairs - $4.8 Billion
U.S. Dept of Homeland Security - $1.2 Billion
U.S. Dept of Transportation - $4.8 Million
U.S. NAVY - $3.8 Billion
NASA - $3.7B
Defense Logistics Agency - $2.9 Billion
Environmental Protection Agency - $112M

Attend our West Coast Summit - and get connected to regional federal
government purchasing.

>> Learn more and register - http://bit.ly/9fbG7a

Our west coast small business supplier summit provides two full days of
opportunity for small businesses including connections to federal agencies
and prime contractors, information about upcoming business, in depth
education, a report on the state of small business federal contracting, and
focused industry-sector one-on-one meetings with federal agencies, prime
contractors and regional resource providers.

PRE-CONFERENCE:
Government Contracting Basics
How to Market Your GSA Schedule

MAIN SESSIONS:
Veteran Affairs Small Business Contracts
E-Verify Requirements
The State of Small Business Federal Contracting
Accessing Assistance from Regional Procurement Center Reps
California Dept of Transportation
Marine Corps Small Business Contracts
NASA Small Business Contracts
Defense Logistics Agency Small Business Contracts
Dept. of Homeland Security Small Business Contracts
Lockheed Martin Small Business Sub-Contracting
EPA Small Business Contracts
BAE, Successful Partnerships

INDUSTRY DAY  
A full day of one-on-one meetings with federal agencies, 
state agencies and prime contractors

>> Learn more and register - http://bit.ly/9fbG7a


+  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +
Register at the NASBC | National Small Business Supplier Registry
+  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +

The National Association of Small Business Contractors hosts the 
National Small Business Supplier Registry -- the national business 
network and connecting place for all small business suppliers who 
provide goods and services to government, prime contractor, and 
corporate buyers.  

Through this registry we connect our small business community, 
provide a focused community to share teaming and sub-contracting, 
and provide a single source location for buyers to research and 
provide additional information on small business suppliers. 

>> Learn more and register - http://bit.ly/bcgTPH


+  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +

Thanks for reading,

Terry Williams, CEO
National Association of Small Business Contractors
Learn about the NASBC - http://bit.ly/bcgTPH

The national trade association supporting America's small
business suppliers

+  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +  +













If you would like to stop receiving these updates, please notify us -
http://bit.ly/bb5yvf


