Delivered-To: aaron@hbgary.com
Received: by 10.239.167.129 with SMTP id g1cs45598hbe;
        Sun, 15 Aug 2010 23:31:54 -0700 (PDT)
Received: by 10.229.11.18 with SMTP id r18mr340857qcr.281.1281940313275;
        Sun, 15 Aug 2010 23:31:53 -0700 (PDT)
Return-Path: <richard.coleman1@comcast.net>
Received: from qmta03.westchester.pa.mail.comcast.net (qmta03.westchester.pa.mail.comcast.net [76.96.62.32])
        by mx.google.com with ESMTP id o6si9947596qcu.100.2010.08.15.23.31.52;
        Sun, 15 Aug 2010 23:31:53 -0700 (PDT)
Received-SPF: pass (google.com: domain of richard.coleman1@comcast.net designates 76.96.62.32 as permitted sender) client-ip=76.96.62.32;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of richard.coleman1@comcast.net designates 76.96.62.32 as permitted sender) smtp.mail=richard.coleman1@comcast.net
Received: from omta12.westchester.pa.mail.comcast.net ([76.96.62.44])
	by qmta03.westchester.pa.mail.comcast.net with comcast
	id uuX91e0020xGWP853uXtaM; Mon, 16 Aug 2010 06:31:53 +0000
Received: from HPATOM ([88.119.100.21])
	by omta12.westchester.pa.mail.comcast.net with comcast
	id uuWR1e0070Thc1U3YuXHdE; Mon, 16 Aug 2010 06:31:51 +0000
From: "Richard Coleman" <richard.coleman1@comcast.net>
To: "'richcoleman1'" <richcoleman1@gmail.com>
Subject: Invitation to Cyber Fajitas with Vice Admiral (Ret) Mike McConnell, The Monocle, Wednesday, September 8, 6:00-8:00pm
Date: Mon, 16 Aug 2010 02:30:25 -0400
Message-ID: <0AF8029614C9409389778D91BAC64562@HPATOM>
MIME-Version: 1.0
Content-Type: multipart/related;
	boundary="----=_NextPart_000_0257_01CB3CEB.2E930800"
X-Mailer: Microsoft Office Outlook 11
Thread-Index: Acs9DFnHTLjkGxDrQCWcvRRqBKl86g==
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.5579

This is a multi-part message in MIME format.

------=_NextPart_000_0257_01CB3CEB.2E930800
Content-Type: multipart/alternative;
	boundary="----=_NextPart_001_0258_01CB3CEB.2E930800"


------=_NextPart_001_0258_01CB3CEB.2E930800
Content-Type: text/plain;
	charset="US-ASCII"
Content-Transfer-Encoding: 7bit

Dear Cyber Security Colleague:  

 

Please join us for the next Cyber Fajitas & Margaritas dinner on Wednesday,
September 8, 6pm - 8pm.

 

Our speaker will be Vice Admiral (Ret) Mike McConnell, Executive Vice
President of Booz Allen Hamilton, former Director National Intelligence and
former Director, National Security Agency.


The event is being held at THE MONOCLE (not our traditional fajitas
restaurant), 107 D Street, NE, Washington, DC 202-5456-4488 (on the Senate
side, just opposite Russell Senate Office Building, nearest Metro stop is
Union Station).  This will be a no sponsor dinner and price is $50 for
dinner and iced tea / lemonade.  Cash bar. 

Please RSVP no later than Wednesday, September 1, seats are limited.

Best regards,
Rich Coleman

Chairman

Cyber Fajitas & Margaritas
Email:  richcoleman1@gmail.com
Phone:  703-855-3917

 

 


------=_NextPart_001_0258_01CB3CEB.2E930800
Content-Type: text/html;
	charset="US-ASCII"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Dus-ascii" =
http-equiv=3DContent-Type>
<STYLE><!-- body, P.msoNormal, LI.msoNormal, PRE, BLOCKQUOTE, a, MENU, =
dd, UL, DT { font-family: "Arial"; font-size: 12pt; margin-top: 0em; =
margin-bottom: 0em; color: #000000; } dir, ADDRESS, h1, h2, h3, h4, h5, =
h6, HR { font-family: "Arial"; font-size: 12pt; margin-top: 0em; =
margin-bottom: 0em; color: #000000; } --></STYLE>

<META name=3DGENERATOR content=3D"MSHTML 8.00.6001.18876"></HEAD>
<BODY id=3DridBody background=3Dcid:421115803@16082010-2A91><FONT =
color=3D#0000ff=20
face=3D"Times New Roman"><?xml:namespace prefix =3D o ns =3D=20
"urn:schemas-microsoft-com:office:office" /><o:p><FONT=20
face=3D"Times New Roman"><SPAN><STRONG><FONT color=3D#0000ff>Dear Cyber =
Security=20
Colleague:&nbsp; <o:p></o:p></FONT></STRONG></SPAN>
<P style=3D"MARGIN: 0in 0in 0pt" class=3DMsoNormal><SPAN=20
style=3D"FONT-FAMILY: Arial; COLOR: navy"><o:p><STRONG><FONT =
color=3D#0000ff=20
face=3D"Times New Roman">&nbsp;</FONT></STRONG></o:p></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt" class=3DMsoNormal><SPAN=20
style=3D"COLOR: navy"><STRONG><FONT face=3D"Times New Roman"><FONT=20
color=3D#0000ff>Please join us for the next Cyber Fajitas &amp; =
Margaritas dinner=20
on Wednesday, September 8, 6pm -=20
8pm.<o:p></o:p></FONT></FONT></STRONG></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt" class=3DMsoNormal><SPAN=20
style=3D"FONT-FAMILY: Arial; COLOR: navy"><o:p><STRONG><FONT =
color=3D#0000ff=20
face=3D"Times New Roman">&nbsp;</FONT></STRONG></o:p></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt" class=3DMsoNormal><SPAN=20
style=3D"COLOR: navy"><STRONG><FONT face=3D"Times New Roman"><FONT =
color=3D#0000ff>Our=20
speaker will be Vice Admiral (Ret) Mike McConnell, Executive Vice =
President of=20
Booz Allen Hamilton, former Director National Intelligence and former =
Director,=20
National Security Agency.<o:p></o:p></FONT></FONT></STRONG></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt" =
class=3DMsoNormal><SPAN><BR><STRONG><FONT=20
face=3D"Times New Roman"><FONT color=3D#0000ff>The&nbsp;event is being =
held at THE=20
MONOCLE (not our traditional fajitas restaurant), 107 D Street, NE, =
Washington,=20
DC 202-5456-4488 (on the Senate side, just opposite Russell Senate =
Office=20
Building, nearest Metro stop is Union Station).&nbsp; This will be a no =
sponsor=20
dinner and price is $50 for dinner and iced tea / lemonade.<SPAN=20
style=3D"mso-spacerun: yes">&nbsp; </SPAN>Cash bar. <BR><BR>Please RSVP =
no later=20
than Wednesday, September 1, seats are limited.<BR><BR>Best =
regards,<BR>Rich=20
Coleman<BR><BR>Chairman<o:p></o:p></FONT></FONT></STRONG></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt" class=3DMsoNormal><SPAN=20
style=3D"COLOR: navy"><STRONG><FONT face=3D"Times New Roman"><FONT=20
color=3D#0000ff>Cyber Fajitas &amp; Margaritas<BR>Email:&nbsp;=20
richcoleman1@gmail.com<BR>Phone:&nbsp;=20
703-855-3917<o:p></o:p></FONT></FONT></STRONG></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt" class=3DMsoNormal><SPAN=20
style=3D"COLOR: navy"><o:p><FONT=20
face=3D"Times New Roman"><STRONG>&nbsp;</STRONG></FONT></o:p></SPAN></P>
<P style=3D"MARGIN: 0in 0in 0pt"=20
class=3DMsoNormal><STRONG>&nbsp;</STRONG></FONT></o:p></P></FONT></BODY><=
/HTML>

------=_NextPart_001_0258_01CB3CEB.2E930800--

------=_NextPart_000_0257_01CB3CEB.2E930800
Content-Type: image/gif;
	name="tech.gif"
Content-Transfer-Encoding: base64
Content-ID: <421115803@16082010-2A91>

R0lGODlhFAAUAPcAAP//////zP//mf//Zv//M///AP/M///MzP/Mmf/MZv/MM//MAP+Z//+ZzP+Z
mf+ZZv+ZM/+ZAP9m//9mzP9mmf9mZv9mM/9mAP8z//8zzP8zmf8zZv8zM/8zAP8A//8AzP8Amf8A
Zv8AM/8AAMz//8z/zMz/mcz/Zsz/M8z/AMzM/8zMzMzMmczMZszMM8zMAMyZ/8yZzMyZmcyZZsyZ
M8yZAMxm/8xmzMxmmcxmZsxmM8xmAMwz/8wzzMwzmcwzZswzM8wzAMwA/8wAzMwAmcwAZswAM8wA
AJn//5n/zJn/mZn/Zpn/M5n/AJnM/5nMzJnMmZnMZpnMM5nMAJmZ/5mZzJmZmZmZZpmZM5mZAJlm
/5lmzJlmmZlmZplmM5lmAJkz/5kzzJkzmZkzZpkzM5kzAJkA/5kAzJkAmZkAZpkAM5kAAGb//2b/
zGb/mWb/Zmb/M2b/AGbM/2bMzGbMmWbMZmbMM2bMAGaZ/2aZzGaZmWaZZmaZM2aZAGZm/2ZmzGZm
mWZmZmZmM2ZmAGYz/2YzzGYzmWYzZmYzM2YzAGYA/2YAzGYAmWYAZmYAM2YAADP//zP/zDP/mTP/
ZjP/MzP/ADPM/zPMzDPMmTPMZjPMMzPMADOZ/zOZzDOZmTOZZjOZMzOZADNm/zNmzDNmmTNmZjNm
MzNmADMz/zMzzDMzmTMzZjMzMzMzADMA/zMAzDMAmTMAZjMAMzMAAAD//wD/zAD/mQD/ZgD/MwD/
AADM/wDMzADMmQDMZgDMMwDMAACZ/wCZzACZmQCZZgCZMwCZAABm/wBmzABmmQBmZgBmMwBmAAAz
/wAzzAAzmQAzZgAzMwAzAAAA/wAAzAAAmQAAZgAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAFAAUAEAIQwBJCBxI
sKBBAAgTKlyYUCDDhwsdQpwoceLDihYjksh4cSNHjR9BhmzocSQAjCFRflTJkWVGlxZhUiw5UiZE
gzhzBgQAOw==

------=_NextPart_000_0257_01CB3CEB.2E930800--

