Delivered-To: phil@hbgary.com
Received: by 10.223.112.17 with SMTP id u17cs918156fap;
        Thu, 6 Jan 2011 06:58:40 -0800 (PST)
Received: by 10.213.35.3 with SMTP id n3mr12681477ebd.89.1294325919766;
        Thu, 06 Jan 2011 06:58:39 -0800 (PST)
Return-Path: <hbgaryrapidresponse+bncCJjb0c2CHhCesZfpBBoERuC6zg@hbgary.com>
Received: from mail-ew0-f70.google.com (mail-ew0-f70.google.com [209.85.215.70])
        by mx.google.com with ESMTP id w11si4334850eeh.26.2011.01.06.06.58.38;
        Thu, 06 Jan 2011 06:58:39 -0800 (PST)
Received-SPF: neutral (google.com: 209.85.215.70 is neither permitted nor denied by best guess record for domain of hbgaryrapidresponse+bncCJjb0c2CHhCesZfpBBoERuC6zg@hbgary.com) client-ip=209.85.215.70;
Authentication-Results: mx.google.com; spf=neutral (google.com: 209.85.215.70 is neither permitted nor denied by best guess record for domain of hbgaryrapidresponse+bncCJjb0c2CHhCesZfpBBoERuC6zg@hbgary.com) smtp.mail=hbgaryrapidresponse+bncCJjb0c2CHhCesZfpBBoERuC6zg@hbgary.com
Received: by ewy5 with SMTP id 5sf2869096ewy.1
        for <multiple recipients>; Thu, 06 Jan 2011 06:58:38 -0800 (PST)
Received: by 10.213.28.138 with SMTP id m10mr2047792ebc.15.1294325918066;
        Thu, 06 Jan 2011 06:58:38 -0800 (PST)
X-BeenThere: hbgaryrapidresponse@hbgary.com
Received: by 10.213.9.194 with SMTP id m2ls2631956ebm.1.p; Thu, 06 Jan 2011
 06:58:36 -0800 (PST)
Received: by 10.213.104.134 with SMTP id p6mr548698ebo.82.1294325915938;
        Thu, 06 Jan 2011 06:58:35 -0800 (PST)
Received: by 10.213.104.134 with SMTP id p6mr548696ebo.82.1294325915861;
        Thu, 06 Jan 2011 06:58:35 -0800 (PST)
Received: from mail-ey0-f182.google.com (mail-ey0-f182.google.com [209.85.215.182])
        by mx.google.com with ESMTPS id y2si4327229eeh.61.2011.01.06.06.58.35
        (version=TLSv1/SSLv3 cipher=RC4-MD5);
        Thu, 06 Jan 2011 06:58:35 -0800 (PST)
Received-SPF: neutral (google.com: 209.85.215.182 is neither permitted nor denied by best guess record for domain of karen@hbgary.com) client-ip=209.85.215.182;
Received: by eyf6 with SMTP id 6so7385985eyf.13
        for <hbgaryrapidresponse@hbgary.com>; Thu, 06 Jan 2011 06:58:35 -0800 (PST)
MIME-Version: 1.0
Received: by 10.14.17.193 with SMTP id j41mr1086406eej.38.1294325915153; Thu,
 06 Jan 2011 06:58:35 -0800 (PST)
Received: by 10.14.127.206 with HTTP; Thu, 6 Jan 2011 06:58:35 -0800 (PST)
Date: Thu, 6 Jan 2011 06:58:35 -0800
Message-ID: <AANLkTiksNT_g+qmJ2ZVzz4VMOp9J7wkRTyHJQVJcu2R3@mail.gmail.com>
Subject: HBGary Intelligence Report 1611
From: Karen Burke <karen@hbgary.com>
To: HBGARY RAPID RESPONSE <hbgaryrapidresponse@hbgary.com>
X-Original-Sender: karen@hbgary.com
X-Original-Authentication-Results: mx.google.com; spf=neutral (google.com:
 209.85.215.182 is neither permitted nor denied by best guess record for
 domain of karen@hbgary.com) smtp.mail=karen@hbgary.com
Precedence: list
Mailing-list: list hbgaryrapidresponse@hbgary.com; contact hbgaryrapidresponse+owners@hbgary.com
List-ID: <hbgaryrapidresponse.hbgary.com>
List-Help: <http://www.google.com/support/a/hbgary.com/bin/static.py?hl=en_US&page=groups.cs>,
 <mailto:hbgaryrapidresponse+help@hbgary.com>
Content-Type: multipart/alternative; boundary=0016e65b40f665769c04992ebce3

--0016e65b40f665769c04992ebce3
Content-Type: text/plain; charset=windows-1252
Content-Transfer-Encoding: quoted-printable

Good morning. This morning, the Sourcefire-Immunet deal continues to get
coverage, while the hot topic on twitter is the story about hacked ITunes
accounts being sold in China. Take a look at the blogs section -- all
interesting, but I thought the new Symantec white paper/blog had best
potential for comment/blogpost. Also, Army kicks off construction this week
of $1.2B NSA cybersecurity intelligence center in Utah -> we can expect tha=
t
story to get a lot of coverage within government/security pubs. K

*Thursday/January  6, 2011*



*Industry News*
CBR: 2010: The year of malware, cyberwar and hacktivism, says PandaLabs

http://security.cbronline.com/news/2010-the-year-of-malware-cyberwar-and-ha=
cktivism-says-pandalabs-050111

*
*

*Hacked ITunes Accounts Sold Online*

http://china.globaltimes.cn/society/2011-01/609351.html


HelpNetSecurity: SanDisk unveils security software and online backup

 http://www.net-security.org/secworld.php?id=3D10399



*eWeek: Sourcefire Buys Immunet For 21M in Cloud Security Play*

**
http://www.eweek.com/c/a/Security/Sourcefire-Buys-Immunet-for-21M-in-Cloud-=
Security-Play-352817/



*MSNBC: Identity Theft, Data Breaches Jumped 33% in 2010*

http://www.msnbc.msn.com/id/40929975/ns/technology_and_science-security/



*Infosecurity: GSA Falls Short in Four Critical Cybersecurity Areas*

http://www.infosecurity-us.com/view/14956/gsa-falls-short-in-four-critical-=
cybersecurity-areas/



*InfoSecurity: Army Kicks Off Construction of $1.2 billion NSA Cybersecurit=
y
Center: *

http://www.infosecurity-us.com/view/14947/army-kicks-off-construction-of-12=
-billion-nsa-cybersecurity-center/



*H: Flash Player Sandbox Can Be Bypassed:*

http://www.h-online.com/security/news/item/Flash-Player-sandbox-can-be-bypa=
ssed-1164376.html





*Blogs*

* *

*Rapid 7: Become Invisible to Anti-virus Protection*

http://blog.rapid7.com/?p=3D5825

* *

*Sunbelt: DHS Is Going After  Money Mules  *

http://sunbeltblog.blogspot.com/2011/01/dhs-is-going-after-money-mules.html=
?utm_source=3Dfeedburner&utm_medium=3Dfeed&utm_campaign=3DFeed:%2BSunbeltBl=
og%2B(GFI%2BBlog)&twitter=3Dcybfor



*Symantec: Portable Document Format Malware*

http://www.symantec.com/connect/blogs/portable-document-format-malware

New White Paper: Symantec continues to observe a large amount of malware
that exploits PDF vulnerabilities. We see samples using old vulnerabilities=
,
even though those vulnerabilities were found over two years ago and have
already been patched. One of the reasons why such samples are used is the
existence of techniques to avoid antivirus detections by taking advantage o=
f
the PDF specifications. Symantec has been and continues to be on the lookou=
t
for PDF malware to create signatures to detect them.



*Naked Security/Sophos: Google vs. Microsoft*

http://nakedsecurity.sophos.com/2011/01/06/google-versus-microsoft/



*The Hill=92s Congress Blog: Why Ruin Really Necessary Cybersecurity
Legislation with a Really Bad Idea *

http://thehill.com/blogs/congress-blog/technology/136079-why-ruin-really-ne=
cessary-cybersecurity-legislation-with-a-really-bad-idea-



*Edd Blog: Self-Encrypted Drives Set To Become Standard Fare*

http://eddblogonline.blogspot.com/2011/01/self-encrypted-drives-set-to-beco=
me.html



* *

*Competitor News*

Nothing of note.



* *

*Other News of Interest*

* *

*Cyber Security Netwitness To Expand Virginia HQ*

http://www.mfrtech.com/articles/8780.html



*CIOL: Cybersecurity is a diplomatic issue today*

http://www.ciol.com/Security/Vulnerabilities/Interviews/Cyber-security-is-a=
-diplomatic-issue-today/145393/0/=93Cybercrime
has today grown to a level of diplomatic concern, similar to cyber war or
terrorism,=94 says Pamela Warren, CISSP, CIPP, Cybercrime Strategist,
Director, Public Sector & CIP Initiatives, McAfee Inc.






--=20
Karen Burke
Director of Marketing and Communications
HBGary, Inc.
Office: 916-459-4727 ext. 124
Mobile: 650-814-3764
karen@hbgary.com
Twitter: @HBGaryPR
HBGary Blog: https://www.hbgary.com/community/devblog/

--0016e65b40f665769c04992ebce3
Content-Type: text/html; charset=windows-1252
Content-Transfer-Encoding: quoted-printable

<div><br></div><div>Good morning. This morning, the Sourcefire-Immunet deal=
 continues to get coverage, while the hot topic on twitter is the story abo=
ut hacked ITunes accounts being sold in China. Take a look at the blogs sec=
tion -- all interesting, but I thought the new Symantec white paper/blog ha=
d best potential for comment/blogpost. Also, Army kicks off construction th=
is week of $1.2B NSA cybersecurity intelligence center in Utah -&gt; we can=
 expect that story to get a lot of coverage within government/security pubs=
. K</div>
<br clear=3D"all"><p class=3D"MsoNormal"><u>Thursday/January <span style=3D=
"mso-spacerun:yes">=A0</span>6,
2011</u></p>

<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNormal"><b style=3D"mso-bidi-font-weight:normal"><u><span st=
yle=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:black">Industry New=
s</span></u></b></p>

<h1 style=3D"margin:0in;margin-bottom:.0001pt"><span style=3D"font-size:12.=
0pt;
line-height:115%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;=
mso-bidi-font-weight:
normal">CBR: 2010: The year of malware, cyberwar and hacktivism, says Panda=
Labs</span></h1>

<p class=3D"MsoNormal"><a href=3D"http://security.cbronline.com/news/2010-t=
he-year-of-malware-cyberwar-and-hacktivism-says-pandalabs-050111">http://se=
curity.cbronline.com/news/2010-the-year-of-malware-cyberwar-and-hacktivism-=
says-pandalabs-050111</a></p>


<p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal"><br></b>=
</p><p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal">Hack=
ed ITunes
Accounts Sold Online</b></p>

<p class=3D"MsoNoSpacing"><a href=3D"http://china.globaltimes.cn/society/20=
11-01/609351.html">http://china.globaltimes.cn/society/2011-01/609351.html<=
/a></p>

<p class=3D"MsoNoSpacing">=A0</p>

<h1 style=3D"margin-top:.6pt;margin-right:0in;margin-bottom:.6pt;margin-lef=
t:
.6pt"><span style=3D"font-size:12.0pt;line-height:115%;font-family:&quot;Ti=
mes New Roman&quot;,&quot;serif&quot;;
color:black">HelpNetSecurity: SanDisk unveils security software and online
backup</span></h1>

<p class=3D"MsoNoSpacing"><span style=3D"mso-spacerun:yes">=A0</span><a hre=
f=3D"http://www.net-security.org/secworld.php?id=3D10399">http://www.net-se=
curity.org/secworld.php?id=3D10399</a></p>

<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal">eWeek: S=
ourcefire
Buys Immunet For 21M in Cloud Security Play</b></p><p class=3D"MsoNoSpacing=
"><b style=3D"mso-bidi-font-weight:normal"></b> <a href=3D"http://www.eweek=
.com/c/a/Security/Sourcefire-Buys-Immunet-for-21M-in-Cloud-Security-Play-35=
2817/">http://www.eweek.com/c/a/Security/Sourcefire-Buys-Immunet-for-21M-in=
-Cloud-Security-Play-352817/</a></p>


<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal">MSNBC: I=
dentity Theft,
Data Breaches Jumped 33% in 2010</b></p>

<p class=3D"MsoNoSpacing"><a href=3D"http://www.msnbc.msn.com/id/40929975/n=
s/technology_and_science-security/">http://www.msnbc.msn.com/id/40929975/ns=
/technology_and_science-security/</a></p>

<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal">Infosecu=
rity: GSA
Falls Short in Four Critical Cybersecurity Areas</b></p>

<p class=3D"MsoNoSpacing"><a href=3D"http://www.infosecurity-us.com/view/14=
956/gsa-falls-short-in-four-critical-cybersecurity-areas/">http://www.infos=
ecurity-us.com/view/14956/gsa-falls-short-in-four-critical-cybersecurity-ar=
eas/</a></p>


<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal">InfoSecu=
rity: Army
Kicks Off Construction of $1.2 billion NSA Cybersecurity Center: </b></p>

<p class=3D"MsoNoSpacing"><a href=3D"http://www.infosecurity-us.com/view/14=
947/army-kicks-off-construction-of-12-billion-nsa-cybersecurity-center/">ht=
tp://www.infosecurity-us.com/view/14947/army-kicks-off-construction-of-12-b=
illion-nsa-cybersecurity-center/</a></p>


<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNoSpacing"><b style=3D"mso-bidi-font-weight:normal">H: Flash=
 Player
Sandbox Can Be Bypassed:</b></p>

<p class=3D"MsoNoSpacing"><a href=3D"http://www.h-online.com/security/news/=
item/Flash-Player-sandbox-can-be-bypassed-1164376.html">http://www.h-online=
.com/security/news/item/Flash-Player-sandbox-can-be-bypassed-1164376.html</=
a></p>


<p class=3D"MsoNoSpacing">=A0</p>

<p class=3D"MsoNoSpacing">=A0</p>

<div style=3D"mso-element:para-border-div;border:none;border-bottom:dotted =
#7D5500 1.0pt;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in 0in 0in 0in">

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-=
bidi-font-size:12.0pt;
color:black">Blogs</span></u></b></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-=
bidi-font-size:12.0pt;
color:black"><span style=3D"text-decoration:none">=A0</span></span></u></b>=
</p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal"><span style=3D"mso-bid=
i-font-size:12.0pt;
color:black">Rapid 7: Become Invisible to Anti-virus Protection</span></b><=
/p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><span style=3D"mso-bidi-font-size:12.0pt;color:black"><a href=
=3D"http://blog.rapid7.com/?p=3D5825"><span style=3D"text-decoration:none;
text-underline:none">http://blog.rapid7.com/?p=3D5825</span></a></span></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-=
bidi-font-size:12.0pt;
color:black"><span style=3D"text-decoration:none">=A0</span></span></u></b>=
</p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal">Sunbelt: DHS Is Going =
After<span style=3D"mso-spacerun:yes">=A0 </span>Money Mules <span style=3D=
"mso-spacerun:yes">=A0</span></b></p>


<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><a href=3D"http://sunbeltblog.blogspot.com/2011/01/dhs-is-going=
-after-money-mules.html?utm_source=3Dfeedburner&amp;utm_medium=3Dfeed&amp;u=
tm_campaign=3DFeed:%2BSunbeltBlog%2B(GFI%2BBlog)&amp;twitter=3Dcybfor">http=
://sunbeltblog.blogspot.com/2011/01/dhs-is-going-after-money-mules.html?utm=
_source=3Dfeedburner&amp;utm_medium=3Dfeed&amp;utm_campaign=3DFeed:%2BSunbe=
ltBlog%2B(GFI%2BBlog)&amp;twitter=3Dcybfor</a></p>


<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in">=A0</p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal">Symantec: Portable Doc=
ument Format Malware</b></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><a href=3D"http://www.symantec.com/connect/blogs/portable-docum=
ent-format-malware">http://www.symantec.com/connect/blogs/portable-document=
-format-malware</a></p>


<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><span class=3D"apple-style-span"><span style=3D"mso-bidi-font-s=
ize:12.0pt">New White Paper:
Symantec continues to observe a large amount of malware that exploits PDF
vulnerabilities. We see samples using old vulnerabilities, even though thos=
e
vulnerabilities were found over two years ago and have already been patched=
. <span style=3D"background:yellow;mso-highlight:yellow">One of the reasons=
 why such
samples are used is the existence of techniques to avoid antivirus detectio=
ns
by taking advantage of the PDF specifications. Symantec has been and contin=
ues
to be on the lookout for PDF malware to create signatures to detect them.</=
span></span></span></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><span class=3D"apple-style-span"><span style=3D"mso-bidi-font-s=
ize:12.0pt">=A0</span></span></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><span class=3D"apple-style-span"><b style=3D"mso-bidi-font-weig=
ht:normal"><span style=3D"mso-bidi-font-size:12.0pt;color:#333333">Naked Se=
curity/Sophos: Google
vs. Microsoft</span></b></span></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><a href=3D"http://nakedsecurity.sophos.com/2011/01/06/google-ve=
rsus-microsoft/">http://nakedsecurity.sophos.com/2011/01/06/google-versus-m=
icrosoft/</a></p>


<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in">=A0</p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal">The Hill=92s Congress =
Blog: Why Ruin Really
Necessary Cybersecurity Legislation with a Really Bad Idea </b></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><a href=3D"http://thehill.com/blogs/congress-blog/technology/13=
6079-why-ruin-really-necessary-cybersecurity-legislation-with-a-really-bad-=
idea-">http://thehill.com/blogs/congress-blog/technology/136079-why-ruin-re=
ally-necessary-cybersecurity-legislation-with-a-really-bad-idea-</a></p>


<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in">=A0</p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal">Edd Blog: Self-Encrypt=
ed Drives Set To
Become Standard Fare</b></p>

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><a href=3D"http://eddblogonline.blogspot.com/2011/01/self-encry=
pted-drives-set-to-become.html">http://eddblogonline.blogspot.com/2011/01/s=
elf-encrypted-drives-set-to-become.html</a><span style=3D"mso-bidi-font-siz=
e:12.0pt"></span></p>


</div>

<p class=3D"MsoNoSpacing"><span lang=3D"EN" style=3D"color:#333333;mso-ansi=
-language:
EN">=A0</span></p>

<div style=3D"mso-element:para-border-div;border:none;border-bottom:dotted =
#7D5500 1.0pt;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in 0in 0in 0in">

<p class=3D"MsoNormal" style=3D"margin-top:2.9pt;margin-right:0in;margin-bo=
ttom:2.9pt;
margin-left:0in;mso-line-height-alt:10.95pt;mso-outline-level:3;border:none=
;
mso-border-bottom-alt:dotted #7D5500 .5pt;padding:0in;mso-padding-alt:0in 0=
in 0in 0in"><b style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-=
bidi-font-size:12.0pt;
color:black"><span style=3D"text-decoration:none">=A0</span></span></u></b>=
</p>

</div>

<p class=3D"MsoNormal" style=3D"text-align:justify"><b style=3D"mso-bidi-fo=
nt-weight:
normal"><u><span style=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:=
black">Competitor
News</span></u></b></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><s=
pan style=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:black">Nothin=
g of note.</span></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><s=
pan style=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:black">=A0</s=
pan></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><b=
 style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-bidi-font-size=
:12.0pt;
line-height:115%;color:black"><span style=3D"text-decoration:none">=A0</spa=
n></span></u></b></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><b=
 style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-bidi-font-size=
:12.0pt;
line-height:115%;color:black">Other News of Interest</span></u></b></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><b=
 style=3D"mso-bidi-font-weight:normal"><u><span style=3D"mso-bidi-font-size=
:12.0pt;
line-height:115%;color:black"><span style=3D"text-decoration:none">=A0</spa=
n></span></u></b></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><b=
 style=3D"mso-bidi-font-weight:normal">Cyber Security Netwitness To Expand =
Virginia
HQ</b></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><a=
 href=3D"http://www.mfrtech.com/articles/8780.html">http://www.mfrtech.com/=
articles/8780.html</a></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt">=
=A0</p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><b=
 style=3D"mso-bidi-font-weight:normal">CIOL: Cybersecurity is a diplomatic =
issue
today</b></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><a=
 href=3D"http://www.ciol.com/Security/Vulnerabilities/Interviews/Cyber-secu=
rity-is-a-diplomatic-issue-today/145393/0/">http://www.ciol.com/Security/Vu=
lnerabilities/Interviews/Cyber-security-is-a-diplomatic-issue-today/145393/=
0/</a>
=93<span class=3D"apple-style-span"><span style=3D"mso-bidi-font-size:12.0p=
t;
line-height:115%;color:black">Cybercrime has today grown to a level of
diplomatic concern, similar to cyber war or terrorism,=94 says</span></span=
><span class=3D"apple-converted-space"><span style=3D"mso-bidi-font-size:12=
.0pt;line-height:
115%;color:black">=A0<span style=3D"border-style:initial;border-color:initi=
al;
outline-width: 0px;outline-style: initial;outline-color: initial;font-style=
:
inherit"></span></span><span class=3D"apple-style-span"><span style=3D"mso-=
bidi-font-size:
12.0pt;line-height:115%;color:black;border:none windowtext 1.0pt;mso-border=
-alt:
none windowtext 0in;padding:0in;mso-bidi-font-weight:bold">Pamela Warren,
CISSP, CIPP, Cybercrime Strategist, Director, Public Sector &amp; CIP
Initiatives, McAfee Inc.</span></span><span class=3D"apple-converted-space"=
><span style=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:black;bord=
er:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in;mso-bidi-font-weight:bold">=
=A0</span></span></span><span style=3D"mso-bidi-font-size:12.0pt;line-heigh=
t:115%"></span></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><s=
pan style=3D"mso-bidi-font-size:12.0pt;line-height:115%">=A0</span></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><s=
pan style=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:black">=A0</s=
pan></p>

<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt"><s=
pan style=3D"mso-bidi-font-size:12.0pt;line-height:115%;color:black">=A0</s=
pan></p>-- <br><div>Karen Burke</div>
<div>Director of Marketing and Communications</div>
<div>HBGary, Inc.</div><div>Office: 916-459-4727 ext. 124</div>
<div>Mobile: 650-814-3764</div>
<div><a href=3D"mailto:karen@hbgary.com" target=3D"_blank">karen@hbgary.com=
</a></div>
<div>Twitter: @HBGaryPR</div><div>HBGary Blog:=A0<a href=3D"https://www.hbg=
ary.com/community/devblog/" target=3D"_blank">https://www.hbgary.com/commun=
ity/devblog/</a></div><br>

--0016e65b40f665769c04992ebce3--
