Delivered-To: ted@hbgary.com
Received: by 10.229.73.212 with SMTP id r20cs49785qcj;
        Thu, 11 Mar 2010 18:49:50 -0800 (PST)
Received: by 10.142.247.22 with SMTP id u22mr1946631wfh.298.1268362189511;
        Thu, 11 Mar 2010 18:49:49 -0800 (PST)
Return-Path: <adbarr@mac.com>
Received: from asmtpout025.mac.com (asmtpout025.mac.com [17.148.16.100])
        by mx.google.com with ESMTP id 2si4393009pzk.106.2010.03.11.18.49.49;
        Thu, 11 Mar 2010 18:49:49 -0800 (PST)
Received-SPF: pass (google.com: domain of adbarr@mac.com designates 17.148.16.100 as permitted sender) client-ip=17.148.16.100;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of adbarr@mac.com designates 17.148.16.100 as permitted sender) smtp.mail=adbarr@mac.com
MIME-version: 1.0
Content-type: multipart/alternative;
 boundary="Boundary_(ID_PPVFtUEHsuWJ4mD4eywd2w)"
Received: from [192.168.1.5] (ip98-169-51-38.dc.dc.cox.net [98.169.51.38])
 by asmtp025.mac.com
 (Sun Java(tm) System Messaging Server 6.3-8.01 (built Dec 16 2008; 32bit))
 with ESMTPSA id <0KZ5005XNEIYH940@asmtp025.mac.com> for ted@hbgary.com; Thu,
 11 Mar 2010 18:49:48 -0800 (PST)
X-Proofpoint-Spam-Details: rule=notspam policy=default score=0 spamscore=0
 ipscore=0 phishscore=0 bulkscore=6 adultscore=0 classifier=spam adjust=0
 reason=mlx engine=5.0.0-0908210000 definitions=main-1003110262
Subject: =?windows-1252?Q?Re:_ManTech=92s_Bill_Varner_on_H._Christopher_G?=
 =?windows-1252?Q?oodrich=92s_VP,_NSA_Appointment?=
From: Aaron Barr <adbarr@mac.com>
In-reply-to: <82D04E630FDE35448D7707265B09D69CDAE018@chnmicmb04.ManTech.com>
Date: Thu, 11 Mar 2010 21:49:46 -0500
Message-id: <0A268B3D-8419-4F78-9ADF-0CF5CB1B309B@mac.com>
References: <8A3CA83D-6416-46CD-9E2D-D00D569EF50E@mac.com>
 <82D04E630FDE35448D7707265B09D69CDAE018@chnmicmb04.ManTech.com>
To: "Varner, Bill" <Bill.Varner@ManTech.com>
X-Mailer: Apple Mail (2.1077)


--Boundary_(ID_PPVFtUEHsuWJ4mD4eywd2w)
Content-type: text/plain; charset=windows-1252
Content-transfer-encoding: quoted-printable


Its going well.  We are starting to do some hiring finally, mostly right =
now to fill some IO work positions.  The company overall has been =
getting a lot of good press regarding its behavior based malware =
detection products and malware analysis tools.  On the services side Ted =
and I have been working like mad on proposals so in the next few months =
I am hopeful that at least a few of those efforts will pay off and we =
can pull in a more substantial team soon.

I am refining my approach to improving net defense through improving =
threat intelligence.  I am convinced that is really the key to pushing =
forward on improving national cyber security capabilities.  Its not sexy =
in that it requires work and a maturing of capabilities and =
understanding through using the right tools and datasets within a solid =
framework/methodology.  I am excited about the potential, now just =
focused on getting on the right contracts to put it into practice.  In =
the meantime I have built somewhat of a consortium of best of breed =
cyber security companies to work out some of the implementation details. =
 I believe you can't do this, big or small, without strong partnerships. =
 When I heard that NTOC was looking to re-compete a few years early that =
certainly peaked my interest.  That is the right place for such a =
concept.

I would ask how things are going, but from what I read and what I hear =
things are on the rise for ManTech, which I surmise is keeping you very =
busy and satisfied.

I met with Bob a few weeks back at his office to catch up.  He seems =
happy.

Aaron


On Mar 11, 2010, at 9:21 PM, Varner, Bill wrote:

> Thanks, Aaron.
> =20
> How Are things?
> =20
> Bill
> =20
> =20
> From: Aaron Barr [mailto:adbarr@mac.com]=20
> Sent: Thursday, March 11, 2010 8:59 PM
> To: Varner, Bill
> Subject: ManTech=92s Bill Varner on H. Christopher Goodrich=92s VP, =
NSA Appointment
> =20
> Bill,
> =20
> Goes without saying but great hire.  I hear the NTOC contract is comin =
up for early recompete so good timing.
> =20
> Aaron
>=20
> ManTech=92s Bill Varner on H. Christopher Goodrich=92s VP, NSA =
Appointment
> ManTech (NASDAQ: MANT) has appointed H. Christopher Goodrich as Vice =
President for National Security Agency (NSA) Programs in its Mission, =
Cyber and Technology Solutions group. Goodrich will head all ManTech =
activities at NSA including current operations and emerging =
opportunities. "Chris has a long and successful history of support to =
the Intelligence ...
>=20
>=20
> =46rom my iPhone


--Boundary_(ID_PPVFtUEHsuWJ4mD4eywd2w)
Content-type: text/html; charset=windows-1252
Content-transfer-encoding: quoted-printable

<html><head><base href=3D"x-msg://5527/"></head><body style=3D"word-wrap: =
break-word; -webkit-nbsp-mode: space; -webkit-line-break: =
after-white-space; "><div><br></div>Its going well. &nbsp;We are =
starting to do some hiring finally, mostly right now to fill some IO =
work positions. &nbsp;The company overall has been getting a lot of good =
press regarding its behavior based malware detection products and =
malware analysis tools. &nbsp;On the services side Ted and I have =
been&nbsp;working like mad on proposals so in the next few months I am =
hopeful that at least a few of those efforts will pay off and we can =
pull in a more substantial team soon.<div><br></div><div>I am refining =
my approach to improving net defense through improving threat =
intelligence. &nbsp;I am convinced that is really the key to pushing =
forward on improving national cyber security capabilities. &nbsp;Its not =
sexy in that it requires work and a maturing of capabilities and =
understanding through using the right tools and datasets within a solid =
framework/methodology. &nbsp;I am excited about the potential, now just =
focused on getting on the right contracts to put it into practice. =
&nbsp;In the meantime I have built somewhat of a consortium of best of =
breed cyber security companies to work out some of the implementation =
details. &nbsp;I believe you can't do this, big or small, without strong =
partnerships. &nbsp;When I heard that NTOC was looking to re-compete a =
few years early that certainly peaked my interest. &nbsp;That is the =
right place for such a concept.</div><div><br></div><div>I would ask how =
things are going, but from what I read and what I hear things are on the =
rise for ManTech, which I surmise is keeping you very busy and =
satisfied.</div><div><br></div><div>I met with Bob a few weeks back at =
his office to catch up. &nbsp;He seems =
happy.</div><div><br></div><div>Aaron</div><div><br></div><div><br><div><d=
iv>On Mar 11, 2010, at 9:21 PM, Varner, Bill wrote:</div><br =
class=3D"Apple-interchange-newline"><blockquote type=3D"cite"><span =
class=3D"Apple-style-span" style=3D"border-collapse: separate; =
font-family: Helvetica; font-size: medium; font-style: normal; =
font-variant: normal; font-weight: normal; letter-spacing: normal; =
line-height: normal; orphans: 2; text-indent: 0px; text-transform: none; =
white-space: normal; widows: 2; word-spacing: 0px; =
-webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: =
0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: =
auto; -webkit-text-stroke-width: 0px; "><div bgcolor=3D"white" =
lang=3D"EN-US" link=3D"blue" vlink=3D"purple"><div class=3D"Section1"><div=
 style=3D"margin-top: 0in; margin-right: 0in; margin-bottom: 0.0001pt; =
margin-left: 0in; font-size: 12pt; font-family: 'Times New Roman', =
serif; "><span style=3D"font-size: 11pt; font-family: Calibri, =
sans-serif; color: rgb(31, 73, 125); ">Thanks, =
Aaron.<o:p></o:p></span></div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; "><span style=3D"font-size: =
11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); =
"><o:p>&nbsp;</o:p></span></div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; "><span style=3D"font-size: =
11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); ">How =
Are things?<o:p></o:p></span></div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; "><span style=3D"font-size: =
11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); =
"><o:p>&nbsp;</o:p></span></div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; "><span style=3D"font-size: =
11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); =
">Bill<o:p></o:p></span></div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; "><span style=3D"font-size: =
11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); =
"><o:p>&nbsp;</o:p></span></div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; "><span style=3D"font-size: =
11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); =
"><o:p>&nbsp;</o:p></span></div><div><div style=3D"border-right-style: =
none; border-bottom-style: none; border-left-style: none; border-width: =
initial; border-color: initial; border-top-style: solid; =
border-top-color: rgb(181, 196, 223); border-top-width: 1pt; =
padding-top: 3pt; padding-right: 0in; padding-bottom: 0in; padding-left: =
0in; "><div style=3D"margin-top: 0in; margin-right: 0in; margin-bottom: =
0.0001pt; margin-left: 0in; font-size: 12pt; font-family: 'Times New =
Roman', serif; "><b><span style=3D"font-size: 10pt; font-family: Tahoma, =
sans-serif; ">From:</span></b><span style=3D"font-size: 10pt; =
font-family: Tahoma, sans-serif; "><span =
class=3D"Apple-converted-space">&nbsp;</span>Aaron Barr =
[mailto:adbarr@mac.com]<span =
class=3D"Apple-converted-space">&nbsp;</span><br><b>Sent:</b><span =
class=3D"Apple-converted-space">&nbsp;</span>Thursday, March 11, 2010 =
8:59 PM<br><b>To:</b><span =
class=3D"Apple-converted-space">&nbsp;</span>Varner, =
Bill<br><b>Subject:</b><span =
class=3D"Apple-converted-space">&nbsp;</span>ManTech=92s Bill Varner on =
H. Christopher Goodrich=92s VP, NSA =
Appointment<o:p></o:p></span></div></div></div><div style=3D"margin-top: =
0in; margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; =
font-size: 12pt; font-family: 'Times New Roman', serif; =
"><o:p>&nbsp;</o:p></div><div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; =
">Bill,<o:p></o:p></div></div><div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; =
"><o:p>&nbsp;</o:p></div></div><div><div style=3D"margin-top: 0in; =
margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; font-size: =
12pt; font-family: 'Times New Roman', serif; ">Goes without saying but =
great hire. &nbsp;I hear the NTOC contract is comin up for early =
recompete so good timing.<o:p></o:p></div></div><div><div =
style=3D"margin-top: 0in; margin-right: 0in; margin-bottom: 0.0001pt; =
margin-left: 0in; font-size: 12pt; font-family: 'Times New Roman', =
serif; "><o:p>&nbsp;</o:p></div></div><div><div style=3D"margin-top: =
0in; margin-right: 0in; margin-bottom: 0.0001pt; margin-left: 0in; =
font-size: 12pt; font-family: 'Times New Roman', serif; =
">Aaron<br><br><a =
href=3D"http://feedproxy.google.com/~r/GovconWire/~3/uYlW9mhSRa0/" =
style=3D"color: blue; text-decoration: underline; "><b>ManTech=92s Bill =
Varner on H. Christopher Goodrich=92s VP, NSA =
Appointment</b></a><br>ManTech (NASDAQ: MANT) has appointed H. =
Christopher Goodrich as Vice President for National Security Agency =
(NSA) Programs in its Mission, Cyber and Technology Solutions group. =
Goodrich will head all ManTech activities at NSA including current =
operations and emerging opportunities. "Chris has a long and successful =
history of support to the Intelligence ...<img border=3D"0" width=3D"1" =
height=3D"1" id=3D"_x0000_i1025" =
src=3D"http://feeds.feedburner.com/~r/GovconWire/~4/uYlW9mhSRa0"><o:p></o:=
p></div></div><div><div style=3D"margin-top: 0in; margin-right: 0in; =
margin-bottom: 0.0001pt; margin-left: 0in; font-size: 12pt; font-family: =
'Times New Roman', serif; "><br><br>=46rom my =
iPhone<o:p></o:p></div></div></div></div></span></blockquote></div><br></d=
iv></body></html>=

--Boundary_(ID_PPVFtUEHsuWJ4mD4eywd2w)--
