Delivered-To: aaron@hbgary.com
Received: by 10.204.81.218 with SMTP id y26cs79806bkk;
        Wed, 20 Oct 2010 13:10:25 -0700 (PDT)
Received: by 10.150.178.18 with SMTP id a18mr1961489ybf.449.1287605424124;
        Wed, 20 Oct 2010 13:10:24 -0700 (PDT)
Return-Path: <martin@hbgary.com>
Received: from mail-gx0-f182.google.com (mail-gx0-f182.google.com [209.85.161.182])
        by mx.google.com with ESMTP id p1si4540800ybn.57.2010.10.20.13.10.23;
        Wed, 20 Oct 2010 13:10:24 -0700 (PDT)
Received-SPF: neutral (google.com: 209.85.161.182 is neither permitted nor denied by best guess record for domain of martin@hbgary.com) client-ip=209.85.161.182;
Authentication-Results: mx.google.com; spf=neutral (google.com: 209.85.161.182 is neither permitted nor denied by best guess record for domain of martin@hbgary.com) smtp.mail=martin@hbgary.com
Received: by gxk3 with SMTP id 3so1744065gxk.13
        for <aaron@hbgary.com>; Wed, 20 Oct 2010 13:10:23 -0700 (PDT)
Received: by 10.150.187.18 with SMTP id k18mr1929946ybf.178.1287605422511;
        Wed, 20 Oct 2010 13:10:22 -0700 (PDT)
Return-Path: <martin@hbgary.com>
Received: from [192.168.1.4] (173-160-19-210-Sacramento.hfc.comcastbusiness.net [173.160.19.210])
        by mx.google.com with ESMTPS id n48sm479899yha.7.2010.10.20.13.10.18
        (version=TLSv1/SSLv3 cipher=RC4-MD5);
        Wed, 20 Oct 2010 13:10:19 -0700 (PDT)
Message-ID: <4CBF4C96.9070902@hbgary.com>
Date: Wed, 20 Oct 2010 13:09:58 -0700
From: Martin Pillion <martin@hbgary.com>
User-Agent: Thunderbird 2.0.0.24 (Windows/20100228)
MIME-Version: 1.0
To: Aaron Barr <aaron@hbgary.com>
Subject: [Fwd: KLINK Pre-release released on the ARC]
X-Enigmail-Version: 0.96.0
OpenPGP: id=49F53AC1
Content-Type: multipart/mixed;
 boundary="------------080203010702030701010000"

This is a multi-part message in MIME format.
--------------080203010702030701010000
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit


Looks to be something HBG Federal could do.

- Martin

--------------080203010702030701010000
Content-Type: message/rfc822;
 name="KLINK Pre-release released on the ARC.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename="KLINK Pre-release released on the ARC.eml"

X-Account-Key: account2
X-Mozilla-Keys: 
Delivered-To: martin@hbgary.com
Received: by 10.229.43.19 with SMTP id u19cs97785qce;
        Wed, 20 Oct 2010 11:35:05 -0700 (PDT)
Received: by 10.229.221.131 with SMTP id ic3mr6765018qcb.152.1287599704066;
        Wed, 20 Oct 2010 11:35:04 -0700 (PDT)
Return-Path: <NSAARC@nsaarc.net>
Received: from AKRON.nsaarc.net ([208.250.53.226])
        by mx.google.com with ESMTP id r17si1168964qcs.194.2010.10.20.11.35.00;
        Wed, 20 Oct 2010 11:35:04 -0700 (PDT)
Received-SPF: neutral (google.com: 208.250.53.226 is neither permitted nor denied by best guess record for domain of NSAARC@nsaarc.net) client-ip=208.250.53.226;
Authentication-Results: mx.google.com; spf=neutral (google.com: 208.250.53.226 is neither permitted nor denied by best guess record for domain of NSAARC@nsaarc.net) smtp.mail=NSAARC@nsaarc.net
Received: from ohio.nsaarc.net (192.168.0.205) by AKRON.nsaarc.net
 (192.168.0.13) with Microsoft SMTP Server id 8.2.254.0; Wed, 20 Oct 2010
 14:34:18 -0400
Message-ID: <7432552.1287599658534.JavaMail.root@192.168.0.13>
Date: Wed, 20 Oct 2010 14:34:18 -0400
From: ARC Webmaster <nsaarc@nsaarc.net>
To: martin@hbgary.com
Subject: KLINK Pre-release released on the ARC
MIME-Version: 1.0
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
X-Mailer: 5e8f9ff01d27a4110d362b36c921858a 5371 2561311
Return-Path: nsaarc@nsaarc.net

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=
=3Diso-8859-1"><meta http-equiv=3D"Content-Script-Type" content=3D"text/jav=
ascript"><meta http-equiv=3D"Content-Style-Type" content=3D"text/css"><meta=
 http-equiv=3D"content-language" content=3D"en"><title>ARC E-MAIL</title></=
head><body><br>(REQUIRED): Please click the link below to confirm your rece=
ipt of this email. If you do not confirm electronically, the ARC staff may =
contact you by phone to insure receipt.<br><br><a href=3D"https://www.nsaar=
c.net/receipt/Confirm?key=3D2561311&sid=3D9b5a120c327703c9f841b12e2cd397a8"=
 target=3D"_blank">Click Here</a> to confirm that you received this email.<=
br><br>_______________________________________________<br><br>Dear HBGARY F=
EDERAL, INC.,<br><br>The National Security Agency wishes to inform you of a=
n opportunity for business with us on a classified project. The Pre-release=
 for KLINK has been added to the current acquisition listings at our Acquis=
ition Resource Center (ARC) in Hanover, MD.<br><br>This will be a classifie=
d acquisition and all information pertaining to it will be kept within SCI =
channels.<br><br>The following Pre-release documents are now available on t=
he ARC:
<br>- KLINK<br><br>(U/FOUO) The purpose of this Market Survey is to identif=
y those potential vendors that can provide research and technical services =
for software analysis technologies of malicious executable code. The contra=
ctor shall conduct studies of armoring techniques (those that are, or might=
 be, used by malicious code). The contractor shall use this information to =
develop and deliver new analysis techniques to assist across the spectrum o=
f malicious code protection techniques. In addition, the contractor shall e=
xtend debugging technology into a code-harvesting tool for Government use. =
This tool will copy code out of memory as it decrypts and then reconstruct =
a non-encrypted and non-armored version of the software under analysis into=
 an executable. This will allow an analyst to study harvested code, reveali=
ng the instructions in their native, non-armored form. SI Gov/Raytheon is c=
urrently performing the work. It is anticipated that the award will either =
be is a CPFFLOE or FFPLOE contract.<br><br>There are two ways to access thi=
s information:<br><br><b>1. ACCESS VIA NSANET:</b><br><br>If you have acces=
s to the classified NSAnet you may view the information by entering keyword=
 GO ARC and navigating to Acquisition.<br><br><b>2. ACCESS VIA THE ARC:</b>=
<br><br>If you do not have access to the NSAnet you can schedule an appoint=
ment to view and/or receive a copy of the pertinent information at the ARC =
facility by making an appointment online at <a href=3D"https://www.nsaarc.n=
et" target=3D"_blank">www.nsaarc.net</a> and clicking on the [Visit the ARC=
] link.<br><br>Due to the highly sensitive nature of NSA acquisitions, the =
ARC staff are not authorized to distribute documents and/or media by any me=
ans other than those listed above. Thank you for your understanding.<br><br=
>Sincerely,<br><br>The ARC Webmaster<br><br><br><br><span style=3D"color:re=
d;"><em>The information contained herein is for the exclusive use of the or=
iginal recipient. This information is granted for limited distribution with=
in the recipient's place of business for planning purposes only. Further di=
ssemination, whether private or public is prohibited.</em></span><br><br> <=
/body></html>


--------------080203010702030701010000--
