Delivered-To: aaron@hbgary.com
Received: by 10.216.51.82 with SMTP id a60cs338372wec;
        Mon, 1 Feb 2010 10:32:34 -0800 (PST)
Received: by 10.220.122.169 with SMTP id l41mr6102664vcr.115.1265049153591;
        Mon, 01 Feb 2010 10:32:33 -0800 (PST)
Return-Path: <martin@hbgary.com>
Received: from mail-qy0-f174.google.com (mail-qy0-f174.google.com [209.85.221.174])
        by mx.google.com with ESMTP id 33si16165773vws.65.2010.02.01.10.32.32;
        Mon, 01 Feb 2010 10:32:33 -0800 (PST)
Received-SPF: neutral (google.com: 209.85.221.174 is neither permitted nor denied by best guess record for domain of martin@hbgary.com) client-ip=209.85.221.174;
Authentication-Results: mx.google.com; spf=neutral (google.com: 209.85.221.174 is neither permitted nor denied by best guess record for domain of martin@hbgary.com) smtp.mail=martin@hbgary.com
Received: by qyk4 with SMTP id 4so2156259qyk.7
        for <aaron@hbgary.com>; Mon, 01 Feb 2010 10:32:32 -0800 (PST)
Received: by 10.224.18.79 with SMTP id v15mr2215601qaa.181.1265049149688;
        Mon, 01 Feb 2010 10:32:29 -0800 (PST)
Return-Path: <martin@hbgary.com>
Received: from ?10.0.0.59? (cpe-98-150-29-138.bak.res.rr.com [98.150.29.138])
        by mx.google.com with ESMTPS id 4sm9541755qwe.23.2010.02.01.10.32.28
        (version=TLSv1/SSLv3 cipher=RC4-MD5);
        Mon, 01 Feb 2010 10:32:29 -0800 (PST)
Message-ID: <4B671E04.6080004@hbgary.com>
Date: Mon, 01 Feb 2010 10:31:32 -0800
From: Martin Pillion <martin@hbgary.com>
User-Agent: Thunderbird 2.0.0.23 (Windows/20090812)
MIME-Version: 1.0
To: Vera Ted <tedvera@mac.com>, Aaron Barr <aaron@hbgary.com>
Subject: [Fwd: HAP Conference & Exposition]
X-Enigmail-Version: 0.96.0
OpenPGP: id=49F53AC1
Content-Type: multipart/mixed;
 boundary="------------040905000604000207010807"

This is a multi-part message in MIME format.
--------------040905000604000207010807
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit


Not sure if you are on this mail list.  It spams me once a week or so
with intel community related things.

- Martin

--------------040905000604000207010807
Content-Type: message/rfc822;
 name="HAP Conference & Exposition.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename="HAP Conference & Exposition.eml"

X-Account-Key: account2
X-Mozilla-Keys: 
Delivered-To: martin@hbgary.com
Received: by 10.90.80.5 with SMTP id d5cs213257agb;
        Mon, 1 Feb 2010 10:20:47 -0800 (PST)
Received: by 10.224.98.197 with SMTP id r5mr2200792qan.277.1265048444904;
        Mon, 01 Feb 2010 10:20:44 -0800 (PST)
Return-Path: <nsaarc@nsaarc.net>
Received: from mail.nsaarc.net (mail.nsaarc.net [208.250.53.230])
        by mx.google.com with ESMTP id 9si6045871qyk.94.2010.02.01.10.20.44;
        Mon, 01 Feb 2010 10:20:44 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of nsaarc@nsaarc.net designates 208.250.53.230 as permitted sender) client-ip=208.250.53.230;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of nsaarc@nsaarc.net designates 208.250.53.230 as permitted sender) smtp.mail=nsaarc@nsaarc.net
Received: from ohio.nsaarc.net (localhost [127.0.0.1])
	by mail.nsaarc.net (Postfix) with ESMTP id 0E38B18AF9D3
	for <martin@hbgary.com>; Mon,  1 Feb 2010 13:20:43 -0500 (EST)
Message-ID: <13605586.1265048443618.JavaMail.root@localhost>
Date: Mon, 1 Feb 2010 13:20:43 -0500 (EST)
From: ARC Webmaster <nsaarc@nsaarc.net>
To: martin@hbgary.com
Subject: HAP Conference & Exposition
Mime-Version: 1.0
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable
X-Mailer: 5e8f9ff01d27a4110d362b36c921858a 4461 1991446

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=
=3Diso-8859-1"><meta http-equiv=3D"Content-Script-Type" content=3D"text/jav=
ascript"><meta http-equiv=3D"Content-Style-Type" content=3D"text/css"><meta=
 http-equiv=3D"content-language" content=3D"en"><title>ARC E-MAIL</title></=
head><body>You are receiving this notification on behalf of the National Se=
curity Agency (NSA) as a result of registering with our Acquisition Resourc=
e Center (ARC) at http://www.nsaarc.net <br><br>Dear Industry Partner,=20
<br>
<br>The 2010 HAP Conference and Expo March 16 - 18, 2010
<br>San Francisco Marriott Marquis
<br>San Francisco, CA
<br>
<br>"Security in a Connected World"
<br>The HAP Conference and Expo is an exciting opportunity for Federal IT d=
ecision makers and technology vendors to learn how the High Assurance Platf=
orm=AE (HAP) initiative is working in collaboration with industry to advanc=
e a new cyber security model that will decisively defeat cyber threats whil=
e offering knowledge workers and war fighters alike more secure information=
 and trusted access to the data and applications they use every day.
<br>
<br>Conference Mission and Objectives:
<br>- Learn how HAP is enabling the transformation of computing - a new app=
roach to cyber security that reliably protects information, networks and ap=
plications in a connected world.
<br>- Understand the HAP roadmap, and discover opportunities to help build =
on and extend this exciting portfolio of Trusted Computing technologies.
<br>- HAP technologies have been deployed in multiple user environments ove=
r the past year. Learn how HAP is delivering Secure, Manageable, Sharing, a=
nd Multi-form factor solutions in these environments.
<br>- See vendor presentations of HAP-related products and technologies and=
 their progress toward HAP commercialization.
<br>- Network with leading experts, vendors and users of cyber security tec=
hnologies.
<br>- IT Decision Makers: Learn how you can pilot HAP technologies in your =
organization, agency or program.
<br>- Technology Vendors: Learn how you can develop and deliver trusted com=
puting-based technologies for the burgeoning cyber security market.
<br>
<br>For more information about the conference, please visit www.ncsi.com. R=
egistration is now open!
<br>
<br>This year's event, unlike previous Forums, will have an attendance fee.=
 Although we would have liked to continue to host a no-cost conference, it =
became clear that we needed additional support to ensure that all attendees=
 received value from the HAP Conference and Expo experience.
<br>
<br>Conference Fees:
<br>
<br>Government Attendees:
<br>$449.00 early registration fee (valid up to six weeks before event begi=
ns)
<br>$499.00 regular registration fee
<br>
<br>Contractor/Industry Attendees:
<br>$529.00 early registration fee (valid up to six weeks before event begi=
ns)
<br>$579.00 regular registration fee
<br>
<br>Regards,
<br>
<br>The ARC Webmaster<br><br><span style=3D"color:red;"><em>The information=
 contained herein is for the exclusive use of the original recipient. This =
information is granted for limited distribution within the recipient's plac=
e of business for planning purposes only. Further dissemination, whether pr=
ivate or public is prohibited.</em></span><br><br> </body></html>


--------------040905000604000207010807--
